-- DROP SCHEMA vetclinic;

CREATE SCHEMA vetclinic AUTHORIZATION postgres;

-- DROP SEQUENCE vetclinic.animals_id_seq;

CREATE SEQUENCE vetclinic.animals_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE vetclinic.owners_owner_id_seq;

CREATE SEQUENCE vetclinic.owners_owner_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE vetclinic.specializations_id_seq;

CREATE SEQUENCE vetclinic.specializations_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE vetclinic.species_id_seq;

CREATE SEQUENCE vetclinic.species_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE vetclinic.vets_id_seq;

CREATE SEQUENCE vetclinic.vets_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE vetclinic.visits_id_seq;

CREATE SEQUENCE vetclinic.visits_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- vetclinic.owners definition

-- Drop table

-- DROP TABLE vetclinic.owners;

CREATE TABLE vetclinic.owners (
	owner_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	full_name varchar(45) NULL,
	age int4 NULL,
	CONSTRAINT owners_pkey PRIMARY KEY (owner_id)
);


-- vetclinic.species definition

-- Drop table

-- DROP TABLE vetclinic.species;

CREATE TABLE vetclinic.species (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(45) NULL,
	CONSTRAINT species_pkey PRIMARY KEY (id)
);


-- vetclinic.vets definition

-- Drop table

-- DROP TABLE vetclinic.vets;

CREATE TABLE vetclinic.vets (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(45) NULL,
	age int4 NULL,
	date_of_graduation date NULL,
	CONSTRAINT vets_pkey PRIMARY KEY (id)
);


-- vetclinic.animals definition

-- Drop table

-- DROP TABLE vetclinic.animals;

CREATE TABLE vetclinic.animals (
	id serial4 NOT NULL,
	"name" varchar(45) NULL,
	date_of_birth date NULL,
	escape_attempts int4 NULL,
	neutered bool NULL,
	weight_kg numeric(10, 4) NULL,
	species_id int4 NULL,
	owner_id int4 NULL,
	CONSTRAINT animals_pkey PRIMARY KEY (id),
	CONSTRAINT fk FOREIGN KEY (species_id) REFERENCES vetclinic.species(id),
	CONSTRAINT fk_owners FOREIGN KEY (owner_id) REFERENCES vetclinic.owners(owner_id)
);


-- vetclinic.specializations definition

-- Drop table

-- DROP TABLE vetclinic.specializations;

CREATE TABLE vetclinic.specializations (
	id serial4 NOT NULL,
	specie_id int4 NULL,
	vet_id int4 NULL,
	CONSTRAINT specializations_pkey PRIMARY KEY (id),
	CONSTRAINT specializations_specie_id_fkey FOREIGN KEY (specie_id) REFERENCES vetclinic.species(id),
	CONSTRAINT specializations_vet_id_fkey FOREIGN KEY (vet_id) REFERENCES vetclinic.vets(id)
);


-- vetclinic.visits definition

-- Drop table

-- DROP TABLE vetclinic.visits;

CREATE TABLE vetclinic.visits (
	id serial4 NOT NULL,
	animal_id int4 NULL,
	vet_id int4 NULL,
	date_of_visit date NULL,
	CONSTRAINT visits_pkey PRIMARY KEY (id),
	CONSTRAINT visits_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES vetclinic.animals(id),
	CONSTRAINT visits_vet_id_fkey FOREIGN KEY (vet_id) REFERENCES vetclinic.vets(id)
);
